Algoritmo "estrutura_condicional_composta(modo feio)"

Var

   hora : inteiro


Inicio
// modo feio:
   escreval("Digite uma hora do dia: ")
   leia(hora)
   
   se hora < 12 entao
      escreval("Bom dia")
   fimse
   
   se (hora >= 12) e (hora < 18) entao
      escreval("Boa tarde")
   fimse
   
   se (hora > 18) entao
      escreval("Boa noite")
   fimse




   


Fimalgoritmo